-- MySQL Script generated by MySQL Workbench
-- Thu Oct 25 12:22:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Delfin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Delfin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Delfin` DEFAULT CHARACTER SET utf8 ;
USE `Delfin` ;

-- -----------------------------------------------------
-- Table `Delfin`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Delfin`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `ApPaterno` VARCHAR(45) NULL,
  `ApMaterno` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Password` VARCHAR(255) NULL,
  `Privilegio` INT NULL,
  `Ciudad` VARCHAR(60) NULL,
  `Pais` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Imagen` VARCHAR(255) NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Delfin`.`Investigaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Delfin`.`Investigaciones` (
  `idInvestigaciones` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL,
  `Hash` VARCHAR(255) NULL,
  `Fecha` DATE NULL,
  `Titulo` VARCHAR(45) NULL,
  `Contenido` LONGTEXT NULL,
  `Tema` VARCHAR(255) NULL,
  PRIMARY KEY (`idInvestigaciones`),
  INDEX `InvestigacionesUsuario_idx` (`idUsuario` ASC),
  CONSTRAINT `InvestigacionesUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Delfin`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Delfin`.`Noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Delfin`.`Noticias` (
  `idNoticias` INT NOT NULL AUTO_INCREMENT,
  `idUsuarios` INT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descripcion` LONGTEXT NULL,
  `Fecha` DATE NULL,
  `Tema` VARCHAR(45) NULL,
  PRIMARY KEY (`idNoticias`),
  INDEX `NoticiasUsuario_idx` (`idUsuarios` ASC),
  CONSTRAINT `NoticiasUsuario`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `Delfin`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Delfin`.`Institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Delfin`.`Institucion` (
  `idInstitucion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(60) NULL,
  PRIMARY KEY (`idInstitucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Delfin`.`Educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Delfin`.`Educacion` (
  `idEducación` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL,
  `idInstitucion` INT NULL,
  `Egreso` VARCHAR(5) NULL,
  `Grado` VARCHAR(45) NULL,
  `Carrera` VARCHAR(45) NULL,
  PRIMARY KEY (`idEducación`),
  INDEX `EducacionUsuario_idx` (`idUsuario` ASC),
  INDEX `Institucion_idx` (`idInstitucion` ASC),
  CONSTRAINT `EducacionUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Delfin`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Institucion`
    FOREIGN KEY (`idInstitucion`)
    REFERENCES `Delfin`.`Institucion` (`idInstitucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Delfin`.`Autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Delfin`.`Autores` (
  `idAutores` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `ApPaterno` VARCHAR(45) NULL,
  `ApMaterno` VARCHAR(45) NULL,
  `idInvestigacion` INT NULL,
  PRIMARY KEY (`idAutores`),
  INDEX `Investigaciones_idx` (`idInvestigacion` ASC),
  CONSTRAINT `Investigaciones`
    FOREIGN KEY (`idInvestigacion`)
    REFERENCES `Delfin`.`Investigaciones` (`idInvestigaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Delfin`.`Mantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Delfin`.`Mantenimiento` (
  `NombreRed` VARCHAR(255) NULL,
  `NombreMesa` VARCHAR(255) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
